### ISSUE TITLE
Issues with images max-width and fonts in Cyrillic

### ISSUE THREAD

**Issue by paskal** [dim0627/hugo_theme_aglaus#16]
Hi!

First is the very same as https://github.com/dim0627/hugo_theme_beg/issues/19
Second, something is wrong with the font, it looks very strange in Russian:

![image](https://user-images.githubusercontent.com/712534/37649615-615c7906-2c43-11e8-988b-68f3f2d1e36f.png)
[Source](https://github.com/paskal/terrty/tree/master/blog) I've built to discover these errors.

**Comment by dim0627** [comment]
Oops, Lato does not support Russian runes 😨 ?

<img width="355" alt="screen shot 2018-03-20 at 21 06 23" src="https://user-images.githubusercontent.com/6571653/37653535-9c9448fc-2c82-11e8-96a6-d359828caba8.png">
