### ISSUE TITLE
The Aglaus Theme Demo is broken on the Hugo Themes website.

### ISSUE THREAD

**Issue by onedrawingperday** [dim0627/hugo_theme_aglaus#17]
Hello @dim0627 

Currently your theme demo fails because since https://github.com/gohugoio/hugo/commit/7930d2132a3c36c1aaca20f16f56978c84656b0a support for `.Source` has been removed from Hugo 0.50 

In your theme's templates please replace all instances of `.Source.Path` with `.File.Path` so that your theme's demo is generated once again.

The above replacement should be done to the following templates:
```
line 12 of layouts/_default/single.html
line 1 of layouts/_default/li.html
line 1 of layouts/_default/li_sm.html
line 1 of layouts/_default/summary.html
line 19 of layouts/_default/baseof.html
```

Please do this and let me know.

Thanks!

CC / @digitalcraftsman

**Comment by onedrawingperday** [comment]
@dim0627 I assume that you also want this theme removed as you said for your other Hugo themes:
https://github.com/dim0627/hugo_theme_solit/issues/9#issuecomment-437540288
https://github.com/dim0627/hugo_theme_robust/issues/37#issuecomment-437540264

Thank you for your replies.

**Comment by dim0627** [comment]
Yes, I think these themes should removed from Hugo Themes because last maintain too old.
Thank you.
