### ISSUE TITLE
Error: unexpected unclosed action in parenthesized pipeline

### ISSUE THREAD

**Issue by SalesforceBobLightning** [dim0627/hugo_theme_aglaus#19]
Hi

Great theme! thanks for sharing.

I've recently run into a problem when I run `hugo` or `hugo server` I get this error message:

`Error: "C:\projects\Hugo\Sites\projectname\themes\hugo_theme_aglaus\layouts\_default\li.html:8:1": parse failed: template: _default/li.html:8: unexpected unclosed action in parenthesized pipeline`

I'm using the latest code for `li.html`

And I am using Hugo v0.54

Any ideas how to fix it?

**Comment by dim0627** [comment]
Hi

Thank you for using my theme.
And I'm so sorry that is bug maybe.

I think this theme does not support Hugo v0.54, because this theme no longer maintain.
Please use other awesome theme 🙇
